on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
        - name: Verifica o repositório do Git...
          uses: actions/checkout@v2

        - name: Instala o node com a versão 14...
          uses: actions/setup-node@v1
          with:
            node-version: 14

        - name: Instalando as dependências...
          run: npm install

        - name: Executando o lint para verificar se há erros.
          run: npx eslint .